"""The Python kernel against the TypeScript kernel's own outputs.

platform/conformance/*.json is generated by the TypeScript kernel
(generate-canonical.mjs, generate-guard.mjs). Every value here must match
byte for byte: a ledger written by a Python worker has to verify under the
TypeScript verifier, and a policy must decide the same effect the same way in
both languages.
"""

import json
from pathlib import Path

import pytest

from polyflow_temporal.canonical import CanonicalError, canonical, digest
from polyflow_temporal.ledger import Ledger, verify_chain
from polyflow_temporal.rules import Guard, classify

CONF = Path(__file__).resolve().parents[2] / "conformance"


def load(name):
    return json.loads((CONF / name).read_text(encoding="utf-8"))


@pytest.mark.parametrize("case", load("canonical.json")["cases"], ids=lambda c: c["name"])
def test_canonical_matches_typescript(case):
    value = json.loads(case["input"])
    if case.get("refused"):
        with pytest.raises(CanonicalError):
            canonical(value)
        return
    assert canonical(value) == case["text"]
    assert digest(value) == case["digest"]


def test_ledger_hashes_match_typescript():
    corpus = load("ledger.json")
    ledger = Ledger(corpus["run"])
    for kind, body, at in corpus["appends"]:
        ledger.append(kind, body, at)
    ours = ledger.events()
    assert [e["hash"] for e in ours] == [e["hash"] for e in corpus["events"]]
    assert verify_chain(corpus["events"])["ok"]


def test_a_tampered_ledger_fails_at_the_edited_event():
    events = load("ledger.json")["events"]
    events[2]["body"]["outcome"] = "allowed"
    assert verify_chain(events) == {"ok": False, "seq": 2, "reason": "hash does not match content"}


@pytest.mark.parametrize("case", load("guard.json")["cases"], ids=lambda c: c["name"])
def test_guard_decides_like_typescript(case):
    policy = case["policy"]
    guard = Guard(policy)
    s = guard.init()
    for i, step in enumerate(case["steps"]):
        op = step["op"]
        where = f"step {i} ({op['op']} {op.get('activity', op.get('name', op.get('id')))})"
        if op["op"] == "decide-commit":
            cls = classify(policy, op["activity"])
            c = {**cls, "target": op["activity"], "argsDigest": digest(op["args"]), "at": op["at"], "proposal": op["proposal"]}
            d = guard.decide(s, c)
            assert {"outcome": d["outcome"], "rules": d["rules"], "approval": d.get("approval")} == step["decision"], where
            assert (digest(d["witness"]) if d.get("witness") else None) == step["witnessDigest"], f"{where}: witness"
            if d["outcome"] == "allow":
                s = guard.commit(s, c, d)
        elif op["op"] == "observe":
            cls = classify(policy, op["activity"])
            s = guard.observe(s, cls["kind"], op["ok"], labels=cls["labels"], result=op.get("result"))
        elif op["op"] == "grant":
            cls = classify(policy, op["activity"])
            s = guard.grant(s, op["id"], cls["kind"], digest(op["args"]), proposal=op["proposal"], at=op["at"])
        elif op["op"] == "signal":
            s = guard.signal(s, op["name"], op["at"])
        elif op["op"] == "void":
            s = guard.void_approval(s, op["id"])
        assert digest(s) == step["stateDigest"], f"{where}: state"


# ---- parity.json: pick (review PYC1) and redact (review PY2) ------------------

from polyflow_temporal.redact import redact  # noqa: E402


@pytest.mark.parametrize("case", load("parity.json")["pick"], ids=lambda c: c["name"])
def test_budget_reads_a_result_like_typescript(case):
    policy = {
        "policy": "p", "version": 1, "digest": "sha256:x", "unlabelled": "deny", "kinds": ["model"],
        "effects": {"llm": {"kind": "model", "class": "none", "labels": []}},
        "rules": [{"id": "m", "type": "budget", "metric": "m", "from": case["from"], "max": 1e9, "outcome": "deny"}],
    }
    g = Guard(policy)
    s = g.observe(g.init(), "model", True, labels=[], result=json.loads(case["result"]))
    assert s["meters"].get("m") == case["meter"]


@pytest.mark.parametrize("case", load("parity.json")["redact"], ids=lambda c: c["name"])
def test_failure_text_is_redacted_like_typescript(case):
    out = redact(json.loads(case["input"]))
    assert out == case["output"]
    assert digest({"error": out}) == digest({"error": case["output"]})


# ---- routes.json: one activity, many tools (plan P7.3a) ------------------------

from polyflow_temporal.rules import PolicyError, check_admitted, policy_body, route_target  # noqa: E402


@pytest.mark.parametrize("case", load("routes.json")["admitted"], ids=lambda c: c["name"])
def test_an_admitted_policy_with_routes_digests_like_typescript(case):
    admitted = case["admitted"]
    assert digest(policy_body(admitted)) == admitted["digest"]
    check_admitted(admitted)
    raw = json.loads(case["raw"])
    assert ("routes" in admitted) == bool(raw.get("routes"))


@pytest.mark.parametrize("case", load("routes.json")["refused"], ids=lambda c: c["name"])
def test_a_route_typescript_refuses_is_refused(case):
    policy = {**load("routes.json")["admitted"][0]["admitted"], "routes": json.loads(case["raw"])["routes"]}
    policy["digest"] = digest(policy_body(policy))  # only the route is wrong
    with pytest.raises(PolicyError, match="routes"):
        check_admitted(policy)


def test_an_edited_admitted_policy_is_refused():
    policy = json.loads(json.dumps(load("routes.json")["admitted"][0]["admitted"]))
    policy["rules"] = []
    with pytest.raises(PolicyError, match="edited"):
        check_admitted(policy)


@pytest.mark.parametrize("case", load("routes.json")["target"], ids=lambda c: c["name"])
def test_route_target_matches_typescript(case):
    policy = {"routes": case["routes"]} if "routes" in case else load("routes.json")["policy"]
    assert route_target(policy, case["activityType"], json.loads(case["args"])) == case["target"]


# ---- P9 security review: routed calls (SEC-UL1) and sealed headers (SEC-SH1/SH2) ----

@pytest.mark.parametrize("case", load("routed-guard.json")["cases"], ids=lambda c: c["name"])
def test_a_routed_undeclared_call_is_denied_like_typescript(case):
    policy = case["policy"]
    guard = Guard(policy)
    s = guard.init()
    for i, step in enumerate(case["steps"]):
        op = step["op"]
        where = f"step {i} ({op['op']} {op.get('activity')})"
        if op["op"] == "decide-commit":
            cls = classify(policy, op["activity"])
            assert cls == step["classification"], where
            c = {**cls, "target": op["activity"], "argsDigest": digest(op["args"]), "at": op["at"], "proposal": op["proposal"]}
            d = guard.decide(s, c)
            assert {"outcome": d["outcome"], "rules": d["rules"], "approval": d.get("approval")} == step["decision"], where
            assert (digest(d["witness"]) if d.get("witness") else None) == step["witnessDigest"], f"{where}: witness"
            if d["outcome"] == "allow":
                s = guard.commit(s, c, d)
        elif op["op"] == "observe":
            cls = classify(policy, op["activity"])
            s = guard.observe(s, cls["kind"], op["ok"], labels=cls["labels"], result=op.get("result"))
        elif op["op"] == "grant":
            cls = classify(policy, op["activity"])
            s = guard.grant(s, op["id"], cls["kind"], digest(op["args"]), proposal=op["proposal"], at=op["at"])
        assert digest(s) == step["stateDigest"], f"{where}: state"


from polyflow_temporal import sealed as sealed_mod  # noqa: E402


@pytest.fixture(params=["default", "pure-python"])
def aead(request, monkeypatch):
    if request.param == "pure-python":
        monkeypatch.setattr(sealed_mod, "aead_seal", sealed_mod._seal_py)
        monkeypatch.setattr(sealed_mod, "aead_open", sealed_mod._open_py)
    return request.param


@pytest.mark.parametrize("case", load("sealed.json")["seal"], ids=lambda c: c["name"])
def test_a_header_seals_like_typescript(case, aead):
    at = case["at"]
    assert sealed_mod.seal_header(case["value"], case["headerKey"], run_id=at["runId"], purpose=at["purpose"], seq=at["seq"]) == case["sealed"]
    keys = {case["headerKey"]["keyId"]: case["headerKey"]["key"]}
    assert digest(sealed_mod.open_header(case["sealed"], keys)) == digest(case["value"])


@pytest.mark.parametrize("case", load("sealed.json")["open"], ids=lambda c: c["name"])
def test_a_header_opens_or_is_refused_like_typescript(case, aead):
    o = case["options"]
    kw = {"required": o.get("required", False), "expect": o.get("expect")}
    if case.get("refused"):
        with pytest.raises(sealed_mod.SealedHeaderError):
            sealed_mod.open_header(case["value"], case["keys"], **kw)
    else:
        assert sealed_mod.open_header(case["value"], case["keys"], **kw) == case["opened"]


from polyflow_temporal.plugin import FileSink  # noqa: E402


@pytest.mark.parametrize("case", load("sink-paths.json")["cases"], ids=lambda c: repr(c["run"]))
def test_a_file_sink_names_files_like_the_typescript_sink(case, tmp_path):
    _, events, _ = FileSink(tmp_path).paths(case["run"])
    assert list(events.relative_to(tmp_path.resolve()).parts) == case["parts"]
