// PolyflowPlugin — the one line a Temporal customer adds (technical spec §5.1).
//
//   Worker.create({ plugins: [new PolyflowPlugin({ sink: fileSink('./ledger') })], ... })
//
// It contributes a workflow interceptor module (generated per configuration,
// because the workflow isolate cannot read files or receive objects), the
// activity-side exporter, and the flush activity. List it LAST among a worker's
// plugins: its interceptor module is then innermost, so the guard sees the
// final activity input every other plugin produced; the worker refuses to run
// if anything is registered after it. A pre-built bundle is accepted only if it
// was built with THIS plugin's configuration.

import { mkdirSync, mkdtempSync, writeFileSync, existsSync, readFileSync, renameSync, lstatSync } from 'node:fs';
import { createRequire } from 'node:module';
import { join, dirname, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { defaultPayloadConverter } from '@temporalio/common';
import { digest, verifyChain, admitPolicy, openHeader } from '@cognitive-fab/polyflow-kernel';
import { LEDGER_HEADER, FLUSH_ACTIVITY } from '@cognitive-fab/polyflow-verify/constants';
import { signHead } from '@cognitive-fab/polyflow-verify';
import { signPrincipal } from './principals.mjs';
import { checkMachineDir } from './certificates.mjs';
import { gateActivities } from './gate-activities.mjs';
import { jevActivities, loadBatteries } from './jev.mjs';

const here = dirname(fileURLToPath(import.meta.url));
/** Found in any bundle that includes a generated interceptor module, followed by the configuration's digest. */
const MARK = 'Generated by PolyflowPlugin';

/**
 * The activity-side exporter: reads the ledger delta a workflow attached to an
 * activity's headers, signs the new head, and hands both to the sink. Activity
 * code is not replay-constrained, so this is where the ledger's I/O belongs.
 *
 * It never fails the activity. The history already holds the delta; a sink
 * that is down loses nothing that `polyflow export` cannot rebuild. A sink
 * that reports a CONFLICT (a different event at a seq it already holds) is
 * reported loudly — that is the tamper signal.
 *
 * Two activities scheduled in one workflow task carry consecutive deltas and
 * may start in either order (P6-P8 review SL). A delta that arrives ahead of
 * its predecessor waits, up to `gapWaitMs`, for the sink to catch up before it
 * is written as a gap; a remote sink (no `head`) holds it back itself.
 */
export function exporter({ sink, signingKey = null, onConflict, onError, onEvents, gapWaitMs = 1000, headerKeys = {} } = {}) {
  const report = onConflict ?? ((run, seqs) => console.error(`[polyflow] ledger conflict for ${run.wf}/${run.run} at seq ${seqs.join(',')}`));
  const fail = onError ?? ((err) => console.error(`[polyflow] ledger export failed: ${err?.message}`));
  return (ctx) => ({
    inbound: {
      async execute(input, next) {
        const p = input.headers?.[LEDGER_HEADER];
        if (p && sink) {
          try {
            const info = ctx?.info;
            // Where a data key is configured, a plaintext header came from code
            // that does not hold it: refused, never signed (P9 security SEC-EX2).
            const { events } = openHeader(defaultPayloadConverter.fromPayload(p), headerKeys, {
              required: Object.keys(headerKeys).length > 0, expect: { runId: info?.workflowExecution?.runId, purpose: 'ledger' },
            });
            if (!Array.isArray(events) || events.length === 0) throw new Error('ledger header carries no events');
            const run = events[0].run;
            // The deployment key vouches only for the activity's OWN workflow:
            // any other run named in a header is refused, never signed (review E1).
            if (!info || run.wf !== info.workflowExecution?.workflowId || run.ns !== info.workflowNamespace) {
              throw new Error(`ledger delta names run ${run.ns}/${run.wf}, but the activity belongs to `
                + `${info?.workflowNamespace ?? '?'}/${info?.workflowExecution?.workflowId ?? '?'}: refused, not signed`);
            }
            // A chain START is written by the run that starts it: a delta from
            // seq 0 must name the activity's own run (P9 security SEC-EX1). Later
            // deltas must continue what the sink holds, which is checked below.
            if (events[0].seq === 0 && run.run !== info.workflowExecution?.runId) {
              throw new Error(`ledger delta starts run ${run.run}, but the activity belongs to run ${info.workflowExecution?.runId}: refused, not signed`);
            }
            const internal = verifyChain(events, { from: { seq: events[0].seq - 1, hash: events[0].prev } });
            if (!internal.ok) throw new Error(`ledger delta does not chain at seq ${internal.seq}: ${internal.reason}`);
            // Continuity with what the sink already holds (tech spec §5.3): a
            // delta that skips ahead is written — so the gap shows — but not
            // signed, and reported (review E3).
            // A sink that cannot answer for its head (a remote service shared by
            // many workers) checks continuity itself and refuses a gap.
            const checks = typeof sink.head === 'function';
            const ahead = (h) => (h ? events[0].seq > h.seq + 1 : events[0].seq > 0);
            let held = checks ? await sink.head(run) : null;
            // Its predecessor may be in flight in another activity slot: wait for it, bounded.
            for (const until = Date.now() + gapWaitMs; checks && ahead(held) && Date.now() < until;) {
              await new Promise((r) => setTimeout(r, 25));
              held = await sink.head(run);
            }
            const gap = checks && ahead(held);
            // The first event past what the sink holds must point at the sink's head.
            const nextEvent = held && !gap ? events.find((e) => e.seq === held.seq + 1) : null;
            const continues = !nextEvent || nextEvent.prev === held.hash;
            if (gap) fail(new Error(`ledger gap for ${run.wf}/${run.run}: the sink holds through seq ${held ? held.seq : -1}, this delta starts at ${events[0].seq}`));
            else if (!continues) fail(new Error(`ledger fork for ${run.wf}/${run.run} at seq ${held.seq + 1}`));
            // Sign the head of the events verified here — never a head the payload claims (review E2).
            const signed = signingKey && !gap && continues ? signHead(run, internal.head, signingKey) : null;
            const r = await sink.write(events, signed);
            if (r?.conflicts?.length) report(run, r.conflicts);
            // For tracers and metrics: the events this delivery stored (or the
            // service holds back), once. Never a refused delta's, never a
            // re-delivery's (P6-P8 review, minor).
            else if (onEvents) {
              const written = Number.isInteger(r?.written) ? r.written : events.length;
              const fresh = r?.pending ? events : events.slice(events.length - written);
              if (fresh.length) { try { onEvents(fresh); } catch { /* an observer never fails the activity */ } }
            }
          } catch (err) {
            fail(err);
          }
        }
        return next(input);
      },
    },
  });
}

/** Absolute path with forward slashes: webpack resolves it on every OS. */
const slash = (p) => p.split('\\').join('/');

/**
 * The machine registry, as a CommonJS module of string-literal requires: webpack
 * resolves those statically, and a computed path would become an empty
 * context that fails only at run time (found in spike P0.2).
 */
function registrySource(machines) {
  const lines = [`// ${MARK}: the certified machines bundled into this worker.`, 'module.exports = {'];
  for (const [name, m] of Object.entries(machines)) {
    const f = (k) => JSON.stringify(slash(m.files[k]));
    lines.push(`  ${JSON.stringify(name)}: {`,
      `    module: require(${f('machine')}),`,
      `    contract: require(${f('contract')}),`,
      `    mapper: require(${f('effects')}).effects,`,
      `    manifest: require(${f('manifest')}),`,
      `    descriptor: ${JSON.stringify(m.descriptor)},`,
      '  },');
  }
  lines.push('};', '');
  return lines.join('\n');
}

/** Write the per-configuration workflow interceptor module the bundler will include. */
/** What a generated module is a function of: configuration, machines, and this plugin's own install. */
export const identityOf = (config, machines = {}) => digest({
  config, machines: Object.fromEntries(Object.entries(machines).map(([n, m]) => [n, { files: m.files, descriptor: m.descriptor }])), plugin: slash(here),
}).slice(7, 39);

/** Write atomically: another process bundling from the same path never reads half a file (review M8). */
const writeAtomic = (file, text) => {
  const tmp = `${file}.${process.pid}.tmp`;
  // The module can hold a header data key (P2.6): readable by the worker only.
  writeFileSync(tmp, text, { mode: 0o600 });
  renameSync(tmp, file);
};

/**
 * Where generated modules go. By default a fresh private directory per process
 * (mkdtemp: unique, and 0700 on POSIX), never a shared, predictable path that
 * another local user could create first and swap files in before webpack reads
 * them (P9 security SEC-GM1). A configured `generatedDir` must not be a symlink.
 */
let privateRoot = null;
function generationRoot(generatedDir) {
  if (generatedDir) {
    mkdirSync(generatedDir, { recursive: true });
    if (lstatSync(generatedDir).isSymbolicLink()) throw new Error(`generatedDir ${generatedDir} is a symbolic link: refused`);
    return generatedDir;
  }
  if (!privateRoot) privateRoot = mkdtempSync(join(tmpdir(), 'polyflow-temporal-'));
  return privateRoot;
}

function generateInterceptorModule(config, machines = {}) {
  const identity = identityOf(config, machines);
  const dir = join(generationRoot(config.generatedDir), identity);
  mkdirSync(dir, { recursive: true });
  const file = join(dir, 'polyflow-interceptors.mjs');
  const lines = [
    `// ${MARK} ${identity}. Do not edit: regenerated from the plugin configuration.`,
    `export const POLYFLOW_IDENTITY = ${JSON.stringify(`${MARK} ${identity}`)};`,
    `import { makeInterceptors } from ${JSON.stringify(slash(join(here, 'workflow-interceptors.mjs')))};`,
    `import { governorFor } from ${JSON.stringify(slash(join(here, 'guard-governor.mjs')))};`,
  ];
  if (Object.keys(machines).length) {
    writeAtomic(join(dir, 'polyflow-machines.cjs'), registrySource(machines));
    lines.push(
      `import { registerMachines } from ${JSON.stringify(slash(join(here, 'governed-workflow.mjs')))};`,
      "import machines from './polyflow-machines.cjs';",
      `registerMachines(machines, ${JSON.stringify({ externalMode: config.externalMode ?? 'never', principals: config.principals ?? null, audience: config.audience ?? null })});`,
    );
  }
  if (config.headerKey) {
    // The data keys are NOT in this file (P9 security SEC-KY1): webpack's
    // DefinePlugin puts them into the in-memory bundle at worker start.
    lines.push(
      "const headerKeys = typeof __POLYFLOW_HEADER_KEYS__ !== 'undefined' ? __POLYFLOW_HEADER_KEYS__ : null;",
      `const config = Object.freeze({ ...${JSON.stringify(config)}, headerKeys, headerKey: { keyId: ${JSON.stringify(config.headerKey.keyId)}, key: headerKeys ? headerKeys[${JSON.stringify(config.headerKey.keyId)}] : null } });`,
    );
  } else {
    lines.push(`const config = Object.freeze(${JSON.stringify(config)});`);
  }
  lines.push('export const interceptors = makeInterceptors(config, governorFor);', '');
  writeAtomic(file, lines.join('\n'));
  return file;
}

/** Load a machine directory (polyflow's six-file layout) for bundling. */
export function loadMachineDir(dir) {
  const abs = resolve(dir);
  const descPath = join(abs, 'polyflow.workflow.json');
  if (!existsSync(descPath)) throw new Error(`${abs} has no polyflow.workflow.json`);
  const d = JSON.parse(readFileSync(descPath, 'utf-8'));
  const files = {
    machine: join(abs, d.machine ?? 'machine.cjs'),
    contract: join(abs, d.contract ?? 'contract.json'),
    effects: join(abs, d.effects ?? 'effects.cjs'),
    manifest: join(abs, d.manifest ?? 'effects.manifest.json'),
  };
  for (const [k, f] of Object.entries(files)) if (!existsSync(f)) throw new Error(`machine '${d.name}': missing ${k} file ${f}`);
  // The whole descriptor, minus file paths: stopAction, claimLeaseMs and
  // unstoppable are read by the workflow (P4/P5 review SA).
  const { contract: _c, machine: _m, effects: _e, manifest: _mf, effectInvariants: _ei, invariants: _i, migrate: _mg, policy: _p, observations: _o, ...rest } = d;
  const descriptor = { ...rest, description: d.description ?? '', inputAction: d.inputAction ?? 'START', tools: d.tools ?? {}, key: d.key ?? null };
  return { dir: abs, files, descriptor };
}

export class PolyflowPlugin {
  /**
   * @param {object} o
   * @param {'observe'|'guard'} [o.level]
   * @param {object} [o.policy]      an admitted policy (G1)
   * @param {object} [o.sink]        fileSink(dir) | memorySink() | a service sink
   * @param {object} [o.signingKey]  { keyId, privateKeyPem } — the deployment key
   * @param {boolean} [o.memo]       also write the chain head to the memo at close: one more billable
   *                                  Action per execution, for visibility the sink already gives (default false)
   * @param {'never'|'allowed'|'always'} [o.externalMode]  whether governed orders may be performed outside the worker
   * @param {Record<string,string>} [o.principals]  keyId -> ed25519 public key: approvers, reporters and claimants
   *                                  must present signed principal tokens (plan P5.5)
   * @param {string} [o.audience]    the namespace principal tokens must name (default: the run's namespace)
   * @param {{keyId:string,key:string}} [o.headerKey]  seals ledger headers (plan P2.6). The key is part of the
   *                                  generated interceptor module: keep `generatedDir` private to the worker
   * @param {Record<string,string>} [o.headerKeys]  older keys the exporter may still meet (rotation)
   */
  constructor({ level = 'observe', policy = null, sink = null, signingKey = null, memo = false, machines = {}, trust = null, allowUncertified = false, gate = null, jev = null, externalMode = 'never', principals = null, audience = null, headerKey = null, headerKeys = {}, generatedDir, onConflict, onError, onEvents } = {}) {
    if (level !== 'observe' && level !== 'guard') throw new Error(`unknown level '${level}' (observe | guard)`);
    if (level === 'guard' && !policy) throw new Error('level "guard" needs a policy');
    // Admitted here, in Node, before any worker exists: a policy the kernel
    // refuses never reaches a workflow (FR-GRD.10). The isolate receives the
    // admitted, normalised form, digest included.
    // At level guard an undeclared activity is DENIED unless the policy says
    // otherwise: a guard that allows what it does not know fails open (P9 security SEC-UL1).
    const admitted = policy ? admitPolicy(level === 'guard' && policy.unlabelled === undefined ? { ...policy, unlabelled: 'deny' } : policy) : null;
    if (!['never', 'allowed', 'always'].includes(externalMode)) throw new Error(`externalMode must be never, allowed or always, got '${externalMode}'`);
    this.config = { level, policy: admitted ? JSON.parse(JSON.stringify(admitted)) : null, memo, externalMode, ...(principals ? { principals, audience } : {}), ...(headerKey ? { headerKey: { keyId: headerKey.keyId } } : {}), ...(generatedDir ? { generatedDir } : {}) };
    // Every key the exporter may meet: the current one and those it rotated from.
    this.headerKeys = { ...headerKeys, ...(headerKey ? { [headerKey.keyId]: headerKey.key } : {}) };
    if (headerKey && !(typeof headerKey.keyId === 'string' && Buffer.from(String(headerKey.key ?? ''), 'base64').length === 32)) throw new Error('headerKey is { keyId, key: base64 of 32 bytes }');
    this.sink = sink;
    this.signingKey = signingKey;
    this.hooks = { onConflict, onError, onEvents };
    this.modulePath = null;
    // The version gate's activities need a client for the fleet's namespace.
    this.gate = gate;
    // Jev: the observation activity, and the batteries each machine declares.
    this.jev = jev;
    // G2: machines this worker may run as GovernedWorkflow, name -> directory.
    // A machine runs only with a certificate that is signed by a trusted key
    // and describes exactly the files being bundled (FR-ADM.3). Running
    // uncertified machines is a development mode that must be asked for.
    if (Object.keys(machines).length && !trust && !allowUncertified) {
      throw new Error('machines need a trust store: pass `trust: { keyId: publicKeyPem }` (or `allowUncertified: true` for local development)');
    }
    this.machines = Object.fromEntries(Object.entries(machines).map(([name, dir]) => {
      const m = loadMachineDir(dir);
      if (m.descriptor.name !== name) throw new Error(`machine directory ${m.dir} calls itself '${m.descriptor.name}', registered as '${name}'`);
      const cert = trust ? checkMachineDir(m.dir, trust) : null;
      m.descriptor.certificate = cert ? { buildId: cert.buildId, digest: cert.digest, guarantees: cert.guarantees } : null;
      // With orders performed by agents or people (externalMode), an order is a
      // wait with no clock of its own: say so when the machine arms none (review WT).
      const deadlines = cert?.checks?.find((c) => c.name === 'structural')?.items?.find((i) => i.name === 'order-waits-have-deadlines');
      if (cert && externalMode !== 'never' && deadlines && deadlines.ok !== true) {
        console.warn(`[polyflow] machine '${name}': some order waits arm no deadline; with externalMode '${externalMode}' a run can wait for an agent that never reports`);
      }
      // A machine certified WITH a policy runs only under that policy (P4/P5 review PL).
      const policyFile = join(m.dir, 'policy.json');
      if (existsSync(policyFile)) {
        const raw = JSON.parse(readFileSync(policyFile, 'utf-8'));
        // Compared as enforced: at guard an omitted `unlabelled` is 'deny' (SEC-UL1).
        const certified = admitPolicy(raw.unlabelled === undefined ? { ...raw, unlabelled: 'deny' } : raw);
        if (this.config.level !== 'guard' || this.config.policy?.digest !== certified.digest) {
          throw new Error(`machine '${name}' was certified with policy ${certified.policy} v${certified.version} (${certified.digest}); `
            + `this worker enforces ${this.config.policy ? `${this.config.policy.policy} (${this.config.policy.digest})` : 'no policy'}. Run it at level "guard" with that policy.`);
        }
      }
      // A machine that asks a judge needs a worker that can ask one: without
      // `jev`, polyflow.observe is simply unregistered and every run waits (review JV4).
      if (!jev && existsSync(join(m.dir, 'observations.json'))) {
        throw new Error(`machine '${name}' declares observation batteries: configure the plugin's \`jev\` option to run it`);
      }
      return [name, m];
    }));
    // The gate vets new versions under the same trust as the worker runs them.
    this.gateTrust = { trust, allowUncertified: Boolean(allowUncertified) };
    if (Object.keys(this.machines).length && !principals) {
      console.warn('[polyflow] WARNING: no `principals` trust store: migrate, release, report, claim and propose are open to every client of the namespace, and identities are recorded as claims.');
    }
    if (allowUncertified && Object.keys(this.machines).length) {
      console.warn('[polyflow] WARNING: running UNCERTIFIED machines (allowUncertified). Development only: nothing checked these machines before they run.');
    }
  }

  get name() { return 'polyflow'; }

  /**
   * The build id for Temporal Worker Versioning (FR-ADM.6): derived from the
   * certificates of the machines this worker runs, so the certificate IS the
   * version. null when a machine is uncertified (development mode).
   */
  buildId() {
    const certs = Object.entries(this.machines).map(([n, m]) => [n, m.descriptor.certificate?.buildId ?? null]);
    if (!certs.length || certs.some(([, b]) => !b)) return null;
    return certs.length === 1 ? certs[0][1] : `certs-${digest(Object.fromEntries(certs)).slice(7, 19)}`;
  }

  /** The workflow interceptor module, generated once per configuration. */
  interceptorModule() {
    if (!this.modulePath) this.modulePath = generateInterceptorModule(this.config, this.machines);
    return this.modulePath;
  }

  /**
   * The webpack hook that gives the bundle the header data keys (SEC-KY1). The
   * keys live in the in-memory bundle only; they are never in generated source.
   */
  _keyHook(prev) {
    if (!this.config.headerKey) return prev;
    const req = createRequire(createRequire(import.meta.url).resolve('@temporalio/worker'));
    const webpack = req('webpack');
    const keys = JSON.stringify(this.headerKeys);
    return (config) => {
      const c = prev ? prev(config) : config;
      c.plugins = [...(c.plugins ?? []), new webpack.DefinePlugin({ __POLYFLOW_HEADER_KEYS__: keys })];
      return c;
    };
  }

  /**
   * For callers that bundle ahead of time: pass these to bundleWorkflowCode.
   * With `headerKey`, a pre-built bundle CONTAINS the data keys: it is refused
   * unless the caller says so (`bundleContainsHeaderKeys: true`), and that
   * bundle is then a secret like the keys themselves.
   */
  bundlerOptions({ bundleContainsHeaderKeys = false, ...options } = {}) {
    if (this.config.headerKey && !bundleContainsHeaderKeys) {
      throw new Error('with headerKey, a pre-built bundle would contain the data keys: pass bundleContainsHeaderKeys: true to accept that, and treat the bundle as a secret');
    }
    return {
      ...options,
      workflowInterceptorModules: [...(options.workflowInterceptorModules ?? []), this.interceptorModule()],
      ...(this.config.headerKey ? { webpackConfigHook: this._keyHook(options.webpackConfigHook) } : {}),
    };
  }

  _workflowSide(options, { replay }) {
    if (options.workflowBundle) {
      const b = options.workflowBundle;
      const code = b.code ?? (b.codePath && existsSync(b.codePath) ? readFileSync(b.codePath, 'utf-8') : '');
      // The mark carries the configuration's identity: a bundle generated for a
      // different configuration (observe vs guard, another policy) is refused,
      // or the policy the operator configured would not be the one that runs (review P1).
      if (!code.includes(`${MARK} ${identityOf(this.config, this.machines)}`)) {
        throw new Error(
          'this workflowBundle was not built with this PolyflowPlugin configuration. '
          + 'Build it with bundleWorkflowCode(plugin.bundlerOptions({ workflowsPath })) using the same plugin '
          + 'options, or pass workflowsPath instead.',
        );
      }
    }
    const interceptors = { ...(options.interceptors ?? {}) };
    let bundlerOptions = options.bundlerOptions;
    if (!options.workflowBundle) {
      // Last in the list: the guard sees the final input every other plugin produced.
      interceptors.workflowModules = [...(interceptors.workflowModules ?? []), this.interceptorModule()];
      if (this.config.headerKey) bundlerOptions = { ...(bundlerOptions ?? {}), webpackConfigHook: this._keyHook(bundlerOptions?.webpackConfigHook) };
    }
    if (!replay) {
      interceptors.activity = [...(interceptors.activity ?? []), exporter({ sink: this.sink, signingKey: this.signingKey, headerKeys: this.headerKeys, ...this.hooks })];
    }
    return { ...options, interceptors, ...(bundlerOptions ? { bundlerOptions } : {}) };
  }

  configureWorker(options) {
    // The certificate IS the version (FR-ADM.6): a worker under Worker
    // Versioning runs under its certificates' build id, or not at all (review BV).
    const dep = options.workerDeploymentOptions;
    if (dep?.useWorkerVersioning && Object.keys(this.machines).length) {
      const mine = this.buildId();
      if (!mine) throw new Error('Worker Versioning with uncertified machines: there is no certified build id to run under');
      if (dep.version?.buildId !== mine) throw new Error(`this worker's deployment build id is '${dep.version?.buildId}', but its certificates make it '${mine}'`);
    }
    const out = this._workflowSide(options, { replay: false });
    out.activities = {
      ...(out.activities ?? {}),
      [FLUSH_ACTIVITY]: async () => ({ flushed: true }),
      ...(this.gate?.client ? gateActivities(this.gate.client, { ...this.gateTrust, signer: this.gate.principalKey ? (act) => signPrincipal({ id: this.gate.principalId ?? 'polyflow-gate', roles: ['operator'], aud: this.gate.namespace ?? this.config.audience ?? 'default', act }, this.gate.principalKey) : null }) : {}),
      ...(this.jev ? jevActivities({ ...this.jev, batteries: Object.fromEntries(Object.entries(this.machines).map(([n, m]) => [n, loadBatteries(m.dir, { allowIllustrative: Boolean(this.jev.allowIllustrative) })])) }) : {}),
    };
    return out;
  }

  configureReplayWorker(options) {
    return this._workflowSide(options, { replay: true });
  }

  /**
   * Refuse to run if an interceptor module was registered after ours: it would
   * sit INSIDE the guard and could rewrite an activity input the guard had
   * already decided (review O1). Checkable only here, once every plugin has
   * configured the worker.
   */
  async runWorker(worker, next) {
    const modules = worker.options?.interceptors?.workflowModules;
    if (Array.isArray(modules) && modules.length && !worker.options.workflowBundle) {
      const last = modules.at(-1);
      if (last !== this.interceptorModule()) {
        // Start and stop at once, so the worker releases its connection rather
        // than holding it open in a state nobody can shut down.
        const running = next(worker);
        worker.shutdown();
        await running.catch(() => {});
        throw new Error(`PolyflowPlugin must be the last workflow interceptor module; '${last}' is registered after it. List PolyflowPlugin last.`);
      }
    }
    return next(worker);
  }
}
